### ISSUE TITLE
Please approve puppet/posix_acl

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet-approved-modules#6]
## Puppet Module Approval Request

 - [x] I can confirm I have checked my module against the [Approved module criteria](https://forge.puppet.com/about/approved/criteria) and I think it is a suitable candidate.

Please include the module Github URL *(include namespace and module name)*,
puppet/posix_acl: https://github.com/voxpupuli/puppet-posix_acl

**Comment by Ramesh7** [comment]
Added approved badge, hence closing.
