### ISSUE TITLE
please approve puppet/ca_cert

### ISSUE THREAD

**Issue by h-haaks** [puppetlabs/puppet-approved-modules#8]
## Puppet Module Approval Request

 - [x] I can confirm I have checked my module against the [Approved module criteria](https://forge.puppet.com/about/approved/criteria) and I think it is a suitable candidate.

Github URL: https://github.com/voxpupuli/puppet-ca_cert

**Comment by Ramesh7** [comment]
Added approved badge, hence closing the same.
