### ISSUE TITLE
Please approve puppet/bolt

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet-approved-modules#9]
## Puppet Module Approval Request

 - [x] I can confirm I have checked my module against the [Approved module criteria](https://forge.puppet.com/about/approved/criteria) and I think it is a suitable candidate.

Please include the module Github URL *(include namespace and module name)*,
https://forge.puppet.com/modules/puppet/bolt

**Comment by Ramesh7** [comment]
Added approved badge, hence closing.
